### ISSUE TITLE
Enum that references its own members doesn't pass through onSymbol

### ISSUE THREAD

**Issue by PMunch** [nimterop/nimterop#152] opened 2019-11-07 09:31 UTC
I've got an enum that looks a bit something like this:
```
enum {
    _ONE,
    _TWO,
    _MAX = _TWO,
    _MORE
}
```
The first `_TWO` gets renamed to `TWO` with a rule in `onSymbol`, but `_MAX = _TWO` gets renamed to `MAX = _TWO` which obviously fails. The value of `_MORE` would also be 4 in the Nim code, not sure what the behaviour of C enums are in this case though, but I'm not sure if that's right.

**Comment by genotrance** [comment] 2019-12-19 05:58
Duplicate of https://github.com/nimterop/nimterop/issues/57.

**Comment by genotrance** [comment] 2019-12-21 17:23
Fixed

**Closed by genotrance** 2019-12-21 17:23 UTC
